name: HTML Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Instal HTMLHint
        run: npm install --save-dev stylelint stylelint-config-standard

      - name: Jalankan HTMLHint
        run: htmlhint "**/*.html"
